import "./globals.css";
import { Cairo } from "next/font/google";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import Footer from "@/components/Footer";
import ProviderStore from "@/store/ProviderStore";

const cairo = Cairo({
  subsets: ["arabic"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Warehouse management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ProviderStore>
      <html suppressHydrationWarning>
        <body
          className={`${cairo.className} bg-gray-200 text-gray-900 flex flex-col min-h-screen`}
        >
          <Navbar />
          <main className="flex justify-center md:pl-[90px] relative flex-1">
            <Sidebar />
            <div className="flex-1 max-w-[1300px] px-3 md:px-6 py-2">
              {children}
            </div>
          </main>
          <Footer />
        </body>
      </html>
    </ProviderStore>
  );
}
